# Generated by Django 4.2.3 on 2023-07-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_point_latitude_alter_point_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=16),
        ),
        migrations.AlterField(
            model_name='point',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=16),
        ),
    ]
