# Generated by Django 4.2.3 on 2023-07-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_point_latitude_alter_point_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='point',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
