# Generated by Django 4.2.3 on 2023-07-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_point_latitude_alter_point_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='created_at',
        ),
    ]
