# Generated by Django 4.2.3 on 2023-07-17 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_point_direction_point_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='point',
            name='nom',
        ),
    ]
