# Generated by Django 4.2.3 on 2023-07-18 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='route',
            name='duration',
        ),
    ]
