# Generated by Django 4.2.3 on 2023-07-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_route_distance_remove_route_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='destination_point',
            field=models.FloatField(),
        ),
    ]
