# Generated by Django 4.2.3 on 2023-08-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_route_destination_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='nom',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
